name: Update dependencies
on:
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
  push:
    branches:
      - main-dependencies
jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Configure git
        uses: dawidd6/action-git-user-config@v1
      - name: Pull
        run: |
          git status
          git pull
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
#          cache: 'npm' uncomment when cache issues are resolved https://github.com/actions/cache/issues/698
      - name: Re-create node_modules
        run: |
          rm -rf node_modules
      - name: Run npm install
        run: |
          npm install
      - name: Add node_modules
        working-directory: node_modules
        run: |
          git add .
      - name: commit
        shell: bash
        run: |
          git commit -am "updated npm dependencies"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
