name: Update dependencies
on:
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Configure git
        uses: dawidd6/action-git-user-config@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: NPM CI
        run: |
          npm ci
      - name: Add node_modules
        working-directory: node_modules
        run: |
          git add .
      - name: Commit changes
        shell: bash
        run: |
          git commit -am "updated npm dependencies"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
